variable "project" {
  description = "The name of your Application"
}

variable "aws_api_apis_functions" {
  description = "The lambda {[handler]: file} map generated by nextless"
  type        = map(string)
}

variable "openapi_tpl_path" {
  description = "The filepath of aws-rest-oai.tpl file which generated by nextless"
  type        = string
}

variable "aws_api_apis_build_id" {
  description = "The BUILD_ID of next application"
  type        = string
}

variable "next_dist_dir" {
  description = "The relative or abs path of your Next.js build directory"
  type        = string
}

variable "s3_bucket_name" {
  description = "The bucket name of your S3 bucket to store pages and lambda zips"
  type        = string
}

variable "gateway_endpoint_type" {
  description = "The fendpoint type of current api gateway"
  default     = "REGIONAL"
}

variable "api_gateway_deploy_stage" {
  description = "The name of the deployment stage"
  default     = "live"
}

variable "api_gateway_deploy_variables" {
  description = "A map that defines the stage variables"
  type        = map(string)
  default     = {}
}
