variable "region" {
  description = "AWS Region"
  default     = "us-east-1"
}

variable "lambda_region" {
  description = "AWS Region for Lambda functions"
  default     = "us-east-1"
}

variable "s3_region" {
  description = "AWS Region for Serverless S3 Bucket"
  default     = "us-east-1"
}

variable "project" {
  description = "The name of your Application"
}

variable "static_s3_bucket_name" {
  description = "The bucket name of your Static S3 service"
  default     = "static-vincentu-blog-bucket"
}

variable "s3_serverless_folder" {
  description = "The folder name in the bucket for serverless ouputs"
  default     = "serverless"
}

variable "openapi_tpl_path" {
  description = "The filepath of aws-rest-oai.tpl file which generated by nextless"
}

variable "gateway_endpoint_type" {
  description = "The fendpoint type of current api gateway"
  default     = "REGIONAL"
}

variable "api_gateway_deploy_stage" {
  description = "The name of the deployment stage"
  default     = "live"
}

variable "aws_api_apis_functions" {
  description = "The lambda map list generated by NextJS"
  default     = {}
}

variable "aws_api_apis_build_id" {
  description = "The BUILD_ID of next application"
  default     = ""
}
