name: Test and Release

on:
  push:
    branches:
      - master
    tags:
      - '!*'

jobs:

  test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/aws-rest-apis

    - uses: actions/setup-go@v1
      with:
        go-version: '1.14'
      env:
        GOPATH: ${{ github.workspace }}
  
    - uses: autero1/action-terraform@v0.1.0
      with:
        terraform_version: 0.12.24

    - name: Get dependencies
      working-directory: src/aws-rest-apis/tests
      run: |
        mkdir $GITHUB_WORKSPACE/bin
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        export PATH=$PATH:$GITHUB_WORKSPACE/bin
        dep ensure

    - name: Run tests
      working-directory: src/aws-rest-apis/tests
      run: go test -v -timeout 60m
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
